### ISSUE TITLE
[Feature req] configuration file

### ISSUE THREAD

**Issue by thekoma** [louwrentius/fio-plot#34]
There are a ton of options.
Could be useful to pass a configuration file/ini/yaml instead of a long line.
This could be useful to integrate iterations for multiple jobs:

```yaml
fio:
  - name: pippo
    target: /data
    target_type: directory
    #output
    #template
    block_size: 4k
    iodepth: "1 2 4 8 16 32 64"
    numjobs: "1 2 4 8 16 32 64"
    duration: 60
    modes:
      - randread
      - randwrite
  - name: topolino
    target: /data2
    target_type: directory
    #output
    #template
    block_size: 4k
    iodepth: "1 2 4 8 16 32 64"
    numjobs: "1 2 4 8 16 32 64"
    duration: 60
    modes:
      - randread
      - randwrite
```
